/**
 * @auto/logos-bridge — re-export shim over `@seam/logos-bridge`.
 *
 * Call sites keep importing `@auto/logos-bridge`. Transport, FakeLogos, and wire
 * types come from software-architect. Vehicle-domain integration fixtures stay
 * in this package's `*-integration.test.ts` files.
 *
 * `DiagnosticSolution` is an alias of seam `Solution` (structurally identical).
 */

export type { Solution as DiagnosticSolution } from "@seam/logos-bridge";
export {
  assertWireMetaCompatible,
  compareEngineVersion,
  createLogosBridge,
  createLogosServeClient,
  type ExecFn,
  emptyOntologyLintResult,
  emptyReasonResult,
  FakeLogosBridge,
  type ForecastInput,
  type ForecastResult,
  forecastResultFromWire,
  fromLogosProblemId,
  LOGOS_ERROR_CODES,
  LOGOS_MIN_ENGINE_VERSION,
  LOGOS_SCHEMA_VERSION,
  type LogosBridge,
  type LogosBridgeConfig,
  LogosBridgeError,
  LogosInputError,
  LogosNotAvailableError,
  type LogosProblemInput,
  LogosProtocolError,
  LogosSchemaError,
  type LogosServeClient,
  LogosSolveError,
  LogosTimeoutError,
  type LogosTransport,
  type LogosWireMeta,
  type OntologyLintCatalogEntry,
  type OntologyLintConfig,
  type OntologyLintInput,
  type OntologyLintIssue,
  type OntologyLintResult,
  ontologyLintResultFromWire,
  payloadFromServeReply,
  type RealizeInput,
  type RealizeLimits,
  type RealizeResult,
  type RealizeScopeMeta,
  type ReasonInput,
  type ReasonRealized,
  type ReasonResolution,
  type ReasonResult,
  type ReasonRule,
  type ReviseInput,
  type ReviseResult,
  readWireMeta,
  realizeResultFromWire,
  reasonResultFromWire,
  reviseResultFromWire,
  type ServeReply,
  type ServeRequest,
  type Solution,
  type StrategizeInput,
  type StrategizeResult,
  solutionFromWire,
  strategizeResultFromWire,
  throwIfSchemaValidationFailed,
  throwIfStructuredFailure,
  toForecastFile,
  toLogosProblemId,
  toOntologyLintFile,
  toRealizeFile,
  toReasonFile,
  toReviseFile,
  toStrategizeFile,
  toVerbalizeArgs,
  toWireProblem,
  type VerbalizeInput,
  type VerbalizeResult,
  verbalizeResultFromWire,
} from "@seam/logos-bridge";
